---
- name: install, start, and enable httpd Service
  hosts: localhost
  tasks:
   - name: install httpd package
     ansible.builtin.yum:
       name: httpd
       state: present

   - name: start httpd service
     ansible.builtin.systemd:
       name: httpd
       state: started

   - name: enable httpd package
     ansible.builtin.systemd:
       name: httpd
       enabled: yes
     
